<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com</groupId>
    <artifactId>corretor_redacao_api</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>corretor-redacao-api-domain</module>
        <module>corretor-redacao-api-application</module>
        <module>corretor-redacao-api-gateway</module>
        <module>corretor-redacao-api-entrypoint</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring-boot.version>3.4.4</spring-boot.version>
        <querydsl.version>5.1.0</querydsl.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Centraliza as versões do QueryDSL (Jakarta) -->
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-jpa</artifactId>
                <version>${querydsl.version}</version>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>