services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: corretor_redacao
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: corretor
      MYSQL_PASSWORD: corretor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  corretor-redacao-api:
    build: ./corretor-redacao-api
    container_name: corretor-redacao-api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/corretor_redacao?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: corretor
      SPRING_DATASOURCE_PASSWORD: corretor

    networks:
      - app-network

  corretor-redacao-app:
    build: corretor-redacao-app
    container_name: corretor-redacao-app
    ports:
      - "8081:80"
    depends_on:
      - corretor-redacao-api
    networks:
      - app-network
    environment:
      - VITE_BACKEND=http://localhost:8080

volumes:
  mysql-data:

networks:
  app-network:
