spring:
    application:
        name: corretor-redacao
    datasource:
        url: jdbc:mysql://localhost:3306/corretor_redacao?useSSL=false&serverTimezone=UTC
        username: corretor
        password: corretor
    liquibase:
        enabled: true
        change-log: classpath:db/migration/master.xml